<?php
/**
 *
 * NOTICE OF LICENSE
 *
 *
 * @category   Criteek
 * @package    Criteek_Reviewsystem
 * @copyright  Copyright (c) 2016 Criteek Comm LLC.
 * @author	   Criteek Developer
 * @license    https://www.criteek.tv/terms-of-use CRITEEK TERMS OF USE
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('store.switcher') ?>
</div>
<div>
    <?php echo $this->getChildHtml('grid.filter.form') ?>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
<script type="text/javascript">
//<![CDATA[
    function filterFormSubmit() {
        var filters = $$('#filter_form input', '#filter_form select');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
        }
        var validator  = new Validation('filter_form');
        if (validator.validate()) {
            setLocation('<?php echo $this->getFilterUrl(); ?>filter/'+encode_base64(Form.serializeElements(elements))+'/');
        }
    }
//]]>
</script>
