<?php
/**
 *
 * NOTICE OF LICENSE
 *
 *
 * @category   Criteek
 * @package    Criteek_Reviewsystem
 * @copyright  Copyright (c) 2016 Criteek Comm LLC.
 * @author	   Criteek Developer
 * @license    https://www.criteek.tv/terms-of-use CRITEEK TERMS OF USE
 */

	$to="";
	$from="";
	
	$result_order = 0;
	
	if(!empty($_REQUEST['from']) && !empty($_REQUEST['to'])){
		
		$orders_row = array();
		$filter_type = $_REQUEST['filter_type'];
		$from = $_REQUEST['from'];
		$to = $_REQUEST['to'];		
		$from_date = date('Y-m-d' . ' 00:00:00', strtotime($from));
		$to_date = date('Y-m-d' . ' 23:59:59', strtotime($to));
			$_orderCollections = Mage::getModel('reviewsystem/emailQueue')->getCollection()
			 ->addFieldToFilter('email_time', array('from'=>$from_date, 'to'=>$to_date))
                ->load();
		$result_order = $_orderCollections->count();
		$result_clicked =$_orderCollections->addFieldToFilter('reopened', array('eq'=>1))->getData();
	$result_status = $_orderCollections->addFieldToFilter('uploaded_review', array('eq'=>1))->getData();
		$i=0;
	foreach($_orderCollections as $key=>$single_order) {
			$clicked =$single_order->getReopened();
			$email =$single_order->getCustomerEmail();
			$streamid =$single_order->getProductSku();
			$helper = Mage::helper('reviewsystem');
		$status =$single_order->getStatus();
		$helper->fetchReviewersStatus($streamid ,$email)->message;
	
			if($clicked ==0)
			{
				$clicked= "No";
			}elseif($clicked==1)
			{
				$clicked= "Yes";
			}
			if($helper->fetchReviewersStatus($status ,$email)->message =="Reviewer present")
			{
				 Mage::getModel('reviewsystem/emailQueue')->load($single_order->getId())->addData(array('uploaded_review'=>1))->save();
				$upload= "Yes";
			}else
			{
				$upload= "No";
			}
			if($status ==0)
			{
				$status= "No";
			}else
			{
				$status= "Yes";
			}
     $order = Mage::getModel('sales/order')->load($single_order->getOrderId());
    $Incrementid = $order->getIncrementId();
				$orders_row[] = array(date("m/d/Y",strtotime($single_order->getEmailTime())), $single_order->getProductName(),$Incrementid ,$email,$single_order->getCustomerName(),$status,$clicked,$upload);
		}
	}else{
			$orders_row = array();

			$_orderCollections = Mage::getModel('reviewsystem/emailQueue')->getCollection()
                ->load();
		$result_order = $_orderCollections->count();
		$result_clicked =$_orderCollections->addFieldToFilter('reopened', array('eq'=>1))->getData();
		$result_status = Mage::getModel('reviewsystem/emailQueue')->getCollection()
                ->load()->addFieldToFilter('uploaded_review', array('eq'=>1))->getData();
		$i=0;
		foreach($_orderCollections as $key=>$single_order) {
			$clicked =$single_order->getReopened();
			$email =$single_order->getCustomerEmail();
			$streamid =$single_order->getProductSku();
			$helper = Mage::helper('reviewsystem');
		$status =$single_order->getStatus();
		$helper->fetchReviewersStatus($streamid ,$email)->message;
	
			if($clicked ==0)
			{
				$clicked= "No";
			}elseif($clicked==1)
			{
				$clicked= "Yes";
			}
			if($helper->fetchReviewersStatus($status ,$email)->message =="Reviewer present")
			{
				 Mage::getModel('reviewsystem/emailQueue')->load($single_order->getId())->addData(array('uploaded_review'=>1))->save();
				$upload= "Yes";
			}else
			{
				$upload= "No";
			}
			if($status ==0)
			{
				$status= "No";
			}else
			{
				$status= "Yes";
			}
     $order = Mage::getModel('sales/order')->load($single_order->getOrderId());
    $Incrementid = $order->getIncrementId();
				$orders_row[] = array(date("m/d/Y",strtotime($single_order->getEmailTime())), $single_order->getProductName(),$Incrementid ,$email,$single_order->getCustomerName(),$status,$clicked,$upload);
			
	
		}
		
	}
	
?>

<div id="anchor-content" class="middle">
  <div id="page:main-container">
    <div class="content-header">
      <table cellspacing="0">
        <tbody>
          <tr>
            <td style="width:50%;"><h3 class="icon-head head-report-sales-sales"><?php echo $this->__("Email Analytics");?></h3></td>
            <td class="form-buttons"><button style="" onclick="filterFormSubmit.submit()" class="scalable " type="button" id="id_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"><span>Show Report</span></button></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div>
      <div class="entry-edit">
        <form method="get" action="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" id="filter_form">
          <?php /*?><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /><?php */?>
          <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Filter</h4>
            <div class="form-buttons"></div>
          </div>
          <div id="sales_report_base_fieldset" class="fieldset">
            <div class="hor-scroll">
              <table cellspacing="0" class="form-list">
                <tbody>
                  <tr>
                    <td class="label"><label for="sales_report_from">From <span class="required">*</span></label></td>
                    <td class="value"><input type="text" style="width:110px !important;" class="input-text" title="From" value="<?php echo $from; ?>" id="sales_report_from" name="from" />
                      <img style="" title="Select Date" id="sales_report_from_trig" class="v-middle" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>skin/adminhtml/default/default/images/grid-cal.gif"> 
                      <script type="text/javascript">
            //<![CDATA[
                Calendar.setup({
                    inputField: "sales_report_from",
                    ifFormat: "%m/%e/%y",
                    showsTime: false,
                    button: "sales_report_from_trig",
                    align: "Bl",
                    singleClick : true
                });
            //]]>
            </script></td>
                  </tr>
                  <tr>
                    <td class="label"><label for="sales_report_to">To <span class="required">*</span></label></td>
                    <td class="value"><input type="text" style="width:110px !important;" class=" input-text" title="To" value="<?php echo $to; ?>" id="sales_report_to" name="to" />
                      <img style="" title="Select Date" id="sales_report_to_trig" class="v-middle" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>skin/adminhtml/default/default/images/grid-cal.gif"> 
                      <script type="text/javascript">
						//<![CDATA[
							Calendar.setup({
								inputField: "sales_report_to",
								ifFormat: "%m/%e/%y",
								showsTime: false,
								button: "sales_report_to_trig",
								align: "Bl",
								singleClick : true
							});
						//]]>
            		</script></td>
                  </tr>                 
                </tbody>
              </table>
            </div>
          </div>
        </form>
      </div>
      <script type="text/javascript">
       	 //<![CDATA[
        	var filterFormSubmit  = new varienForm('filter_form');
			function changeStatusOption(optionvalue){
				var filter_date = document.getElementById("hide_for_shipping_date");
				var hide_status_for_shipping_date = document.getElementById("hide_status_for_shipping_date");
				if(optionvalue=="shipping_date"){
					filter_date.className = "no-display";
					hide_status_for_shipping_date.style.display = "none";
				}
				if(optionvalue=="order_date"){
					filter_date.className = "";
				}
			}
         //]]>
        </script> 
      <script type="text/javascript"> new FormElementDependenceController({"sales_report_order_statuses":{"sales_report_show_order_statuses":"1"}}); </script> 
      <style type="text/css">
	  	.no-display{display:none;}
      </style>
    </div>
    
    <div>
    <?php if($result_order>0){?>
      <table cellspacing="0" class="actions">
        <tbody>
          <tr>
                     
<td class="filter-actions a-left">
  Mail sent: <?php echo $result_order?></br>
  Customer clicked on links:  <?php echo count($result_clicked) ?></br>
  Review uploaded:  <?php echo count($result_status) ?></td>
            <td class="pager">&nbsp;</td>
            <td class="export a-right">
            	<form method="post" action="<?php echo $this->getUrl('*/*/exportCsv')?>" id="csv_form">
                	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                	<input type="hidden" value="<?php echo $from; ?>" id="sales_report_from" name="from" />
                    <input type="hidden" value="<?php echo $to; ?>" id="sales_report_to" name="to" /> 
                </form>
                <script type="text/javascript">
				 //<![CDATA[
					var csvFormSubmit  = new varienForm('csv_form');
				 //]]>
				</script> 
            </td>
            <td class="filter-actions a-right">
              <img class="v-middle" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>skin/adminhtml/default/default/images/icon_export.gif">&nbsp; Export to:
              <select style="width:8em;" id="sales_order_grid_export" name="sales_order_grid_export">
                <option value="<?php echo $this->getUrl('*/*/exportCsv')?>">CSV</option>
              </select>
              <button onclick="csvFormSubmit.submit()" class="scalable task" type="button"><span>Export</span></button>
            </td>
          </tr>
        </tbody>
      </table>
    <?php } ?>  
      <div id="id_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" class="print_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <div class="grid">
          <div class="hor-scroll">
            <table cellspacing="0" id="id_<?php echo Mage::getSingleton('core/session')->getFormKey() ?>_table" class="data">
              <colgroup>
              <col>
              <col>
              <col>
              <col>
              <col>
               <col>
               <col>
              <col>
              </colgroup>
              <thead>
                <tr class="headings">
                 <th class=" no-link"><span class="nobr">Date</span></th>
                  <th class=" no-link"><span class="nobr">Product Name</span></th>
                  <th class=" no-link"><span class="nobr">Order Id</span></th>
                  <th class=" no-link"><span class="nobr">Customer Email</span></th>
                  <th class=" no-link"><span class="nobr">Customer Name</span></th>
                  <th class=" no-link"><span class="nobr">Email Send to Customer</span></th>
                  <th class=" no-link"><span class="nobr">Responded By Customer</span></th>
                  <th class=" no-link"><span class="nobr">Review uploaded By Customer</span></th>

        
                </tr>
              </thead>
              <tbody id="">
                <?php
                if(count($orders_row)>0){
					foreach($orders_row as $singlerows){
						if(!empty($singlerows)){
							echo "<tr>";
							foreach($singlerows as $value){
				?>
              				<td><?php echo $value;?></td>
                <?php
							}
							echo "</tr>";
						}
					}
				}else{
				?>
              <tr class="even">
                <td colspan="13" class="empty-text a-center">No records found.</td>
              </tr>
              <?php } ?>
                </tbody>
              
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>